### ISSUE TITLE
Add possibility to disable intcache for specific typoscript page type

### ISSUE THREAD

**Issue by mueller-sebastian** [IchHabRecht/intcache#3]
When calling to another PAGE.type than the intcache one (without ```10.userFunc = IchHabRecht\Intcache\Renderer\IntcacheRenderer->render```), you can not disable the intcache functionality.

The current code does not allow to disable intcache by setting
```
customAjaxStuff = PAGE
customAjaxStuff {
    config.intcache = 0
}
```

**Comment by mueller-sebastian** [comment]
Or is there a reason why ```$this->typoScriptFrontendController->tmpl->setup['config.']['intcache']``` is checked and the new check should be applied additionally?

**Comment by IchHabRecht** [comment]
Hi @mueller-sebastian,

Thank you for your pull request. I will add some functional tests and release a bugfix version with your patch.
