### ISSUE TITLE
Problems with extbase and routeEnhancers

### ISSUE THREAD

**Issue by mueller-sebastian** [IchHabRecht/intcache#5]
When having an not cacheable action of a plugin, which is not the default action,
the intcache extension is not working properly. It is always the default action used.

The problem is that the query string is not added,
because in https://github.com/IchHabRecht/intcache/blob/master/Classes/Hooks/ContentPostProcessHook.php#L103 the value cHash is checked, but because of the used routeEnhancer, there is no cHash in this variable.

`$addQueryStringMethod = $this->typoScriptFrontendController->cHash ? 'GET' : '';`

When manually changed to alwas use GET, the correct action will be used in the intcache replacement.

**Comment by mueller-sebastian** [comment]
I would provide a pull request, but I'm not sure how this can be handled beautiful instead of always setting `$addQueryStringMethod = 'GET';`
Do you have an idea?

**Comment by IchHabRecht** [comment]
Hi @mueller-sebastian,

Thank you for your report. Could you provide more information about your scenario, so I'm able to build up a local test case for your issue?

**Comment by mueller-sebastian** [comment]
The problem is the url the intcache extension generates (`$intcacheLink`) and inserts in the HTML which will be replaced via ajax when using routeEnhancers:

URL without routeEnhancer:
`
https://domain.de/seite?tx_intcache[identifier]=xxxxxxx&tx_places_searchandresultlist[action]=searchAndResultlist&tx_places_searchandresultlist[controller]=Places&tx_places_searchandresultlist[submitted]=1&type=4242&cHash=yyyyyyy
`

URL with routeEnhancer:
`
https://domain.de/seite?tx_intcache%5Bidentifier%5D=xxxxxxx&type=4242&cHash=yyyyyyy
`

URL with routeEnhancer and correct added QueryString (see temporary fix (setting $addQueryStringMethod = 'GET';))
`
https://domain.de/seite/ergebnisse?tx_intcache%5Bidentifier%5D=xxxxxxx&type=4242&cHash=yyyyyyy
`

Since without this fix, no arguments are added (action, controller, neighter as params or enhanced route), the default action will be used.

----
Our setup is:

You have a plugin with multiple actions, where the default action is cacheable, but other actions not:
```
        \TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
            'ElementareTeilchen.Places',
            'SearchAndList',
            [
                'Places' => 'search, searchAndResultlist'
            ],
            // non-cacheable actions
            [
                'Places' => 'searchAndResultlist'
            ]
        );
```
search just displays a form and will send the form to the same page via POST.
searchAndResultlist will display a form and the results.
To have a url for the better searchAndResultlist, one param is added as a argument in the form itself.

```
    <f:form
        action="searchAndResultlist"
        name="search"
        object="{search}"
        method="post"
        arguments="{submitted: 1}"
    >
```

To have a beautifil url, you add a routeEnhancer:
```
routeEnhancers:
  PlacesSearch:
    type: Extbase
    extension: Places
    plugin: SearchAndList
    routes:
      - routePath: '/{submitted}'
        _controller: 'Places::searchAndResultlist'
#    defaultController: 'Places::searchAndResultlist'
    aspects:
      submitted:
        type: StaticValueMapper
        map:
          ergebnisse: 1
```

(the default Controller was just a test but did not help.)


When we are on the result listing page, the content is changed and is handled via Typoscript:
```
[request.getQueryParams()['tx_places_searchandresultlist']['submitted'] == 1]

    lib.content.main >
    lib.content.main = COA
    lib.content.main {

        10 = USER
        10 {
            userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
            pluginName = SearchAndList
            vendorName = ElementareTeilchen
            extensionName = Places
            controller = Places
            action = searchAndResultlist
        }
    }
[end]
```

And here, the intcache extension correctly marks the content as not cacheable and inserts the html which will be replaced via ajax and intcache.
But since the action is not provided in the intcache ajax-url, the resulting HTML contains the output of the default action.


Hopefully this was not to complicated written :-)

**Comment by IchHabRecht** [comment]
Hi @mueller-sebastian,

I finally had some time to setup an example project. I think the problem is not solved with any GET argument in your case. It is the TypoScript condition that is enabled only when the 'submitted' argument is set. intcache doesn't handle any TypoScript anymore - all necessary information are saved when the coa elements are replaced on the main site. In your case this configuration contains the information for rendering the default action of your plugin. There has to be a way to save the correct information for the rendering without any argument. Are you using 2 content elements for the search/result page? Is there any chance to set the correct action in that content element (e.g. flexform configuration)?

**Comment by mueller-sebastian** [comment]
Hi @IchHabRecht,

I don't think it has something to do with the TypoScript condition. This is just our use case where we do something with the params on the destination page. Sorry for confusing you by posting it. When describing our scenario, I just described it all :-)

The generated url from intcache itself is wrong. We have our form viewhelper, where we add an argument (submitted: 1) and have an routeEnhacer which adds "ergebnisse" if submitted = 1.

I have written an test extension for you, where you can see the problem and test with it:
https://github.com/mueller-sebastian/intcachetest

You have to add following site configuration
```
routeEnhancers:
  Example:
    type: Extbase
    extension: intcachetest
    plugin: Example
    routes:
      - routePath: '/{submittedEnhanced}'
        _controller: 'Example::show'
    aspects:
      submittedEnhanced:
        type: StaticValueMapper
        map:
          niceurl: 1
```

There are two links in the default action. The first action does not use the enhanced url (other argument) which works fine. The second link does use the enhanced url. In the html snippet of the page (looked in the source code ) you can see that the intcache url does not have the /niceurl/ part in its url, so the argument is not sent to the action. The action is not provided, so the list action is displayed  

If you change the code temporarily as described in my first comment, the action works correctly, even if intcache is activated.

**Comment by IchHabRecht** [comment]
Hi @mueller-sebastian,

Thank you very much for providing the example extension. I was able to reproduce, analyse and resolve your problem :-)
If you don't mind you could test the branch https://github.com/IchHabRecht/intcache/tree/fix-route-enhancers that should resolve your problems.

**Comment by mueller-sebastian** [comment]
It works, great :-)
I was not sure if $pageArguments->getStaticArguments() would only handle "staticValueMappers" but also works with news and "PersistedAliasMapper" (testet with setting news detail view to not cachable and providing an routeEnhancer).

**Comment by IchHabRecht** [comment]
Hi @mueller-sebastian,

I used the function $pageArguments->getStaticArguments() because I saw it's used in TSFE to create the cache identifier. So I thought this should be the way to go. :-)
